import datetime
current_year = datetime.datetime.now().year


language_keys = {
  # "Copyright @"+str(current_year)+" Indigenous Dubbing": "",
  "Copyright @"+str(current_year)+" Scripture Videos": "",
  "Loading...": "",
  "Choose your Preferred Language": "",
  # "Search Text Here (switch to 'Search...')": "",
  "Search…": "",
  "Online": "",
  "Offline": "",
  "Home": "",
  "Terms Of Use": "",
  "Privacy Policy": "",
  "Feedback": "",
  "Language": "",
  "search_placeholder": "",
  "Available on Device": "",
  "Are you sure you want to delete ?": "",
  "YES": "",
  "No": "",
  "Alert!": "",
  "Alphabetically": "",
  "Downloaded": "",
  "Search Languages": "",
  "Something went wrong": "",
  "Please select your language": "",
  "Search Language": "",
  "Search episodes": "",
  "You\'re offline. Please connect and try again": "",
  "Internet connection restore.": "",
  "No episodes are available.": "",
  "Contact Us": "",
  "available on device": "",
  "This language is already selected.": "",
  "Cancel": "Cancelar",
  "No search result is found.": "",
  "Would you like to watch next episode?": "",
  "No match found!": "",
  "Pause Download": "",
  "Resume Download": "",
  "Cancel Download": "",
  "Enter series name": "",
  "Enter episode position": "",
  "Sort": "",
  "Position": "",
  "Please enter position number.": "",
  "Please enter series name or episode position.": "",
  "Downloading failed.": "",
  "Downloaded successfully.": "",
  "Downloading resumed.": "",
  "Downloading paused.": "",
  "Download canceled.": "",
  "File deleted.": "",
  "Please wait": "",
  "Video not available":""

}